out_dir: results
metric_best: mrr
metric_agg: argmax
tensorboard_each_run: False  # Log to Tensorboard each run
accelerator: "cuda:0"
num_workers: 8
wandb:
  use: False
  project: pcqm4m-contact
dataset:
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_Poly:
  enable: True
  method: mixed_bern
  order: 20
  emb_dim: 22
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: GritTransformer
  loss_fun: cross_entropy
  edge_decoding: dot
gt:
  layer_type: GritTransformer
  layers: 4
  n_heads: 12
  dim_hidden: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.25
  layer_norm: False
  batch_norm: True
  update_e: True
  attn:
    clamp: 5.
    act: relu
    full_attn: True
    edge_enhance: True
    O_e: True
    norm_e: True
gnn:
  head: inductive_edge
  layers_pre_mp: 0
  layers_post_mp: 1
  dim_inner: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
