out_dir: results
metric_best: mrr
metric_agg: argmax
tensorboard_each_run: False  # Log to Tensorboard each run
accelerator: "cuda:0"
num_workers: 8
wandb:
  use: False
  project: pcqm4m-contact
dataset:
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_Poly:
  enable: True
  method: mixed_bern
  order: 8
  emb_dim: 10
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: GseModel
  loss_fun: cross_entropy
  edge_decoding: dot
gse_model:
  enable: True
  hidden_dim: 64
  attn_heads: 8
  drop_prob: 0.0
  attn_drop_prob: 0.2
  residual: True
  layer_norm: False
  batch_norm: True
  bn_momentum: 0.1
  bn_no_runner: False
  rezero: False
  deg_scaler: True
  clamp: 5.0
  weight_fn: softmax
  agg: add
  act: relu
  messaging:
    layer_type: grit
    num_blocks: 4
    repeats: 2
  full:
    layer_type: dense
    enable: True
    repeats: 2
    input_norm: False
  head: inductive_edge
gnn:
  head: inductive_edge
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
