out_dir: results
metric_best: accuracy-SBM
tensorboard_each_run: False  # Log to Tensorboard each run
accelerator: "cuda:0"
num_workers: 4
wandb:
  use: False
  project: CLUSTER
dataset:
  format: PyG-GNNBenchmarkDataset
  name: CLUSTER
  task: graph
  task_type: classification
  transductive: False
  split_mode: standard
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
  precompute_on_the_fly: True
posenc_Poly:
  enable: True
  method: deco_bern
  power: 30
  add_full_edge_index: True
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: MbpModel
  loss_fun: weighted_cross_entropy
  edge_decoding: dot
mbp_model:
  enable: True
  hidden_dim: 56
  attn_heads: 8
  drop_prob: 0.01
  attn_drop_prob: 0.5
  residual: True
  layer_norm: False
  batch_norm: True
  bn_momentum: 0.1
  bn_no_runner: False
  rezero: False
  deg_scaler: True
  clamp: 5.0
  weight_fn: softmax
  agg: add
  act: relu
  pe_layer: simple_linear
  poly:
    layer_type: cattn
    num_blocks: 0
    repeats: 0
  full:
    layer_type: cattn
    enable: True
    repeats: 15
    input_norm: False
gnn:
  head: inductive_node
  layers_post_mp: 3
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 150
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
