out_dir: results
metric_best: mrr
metric_agg: argmax
tensorboard_each_run: False  # Log to Tensorboard each run
accelerator: "cuda:0"
num_workers: 4
wandb:
  use: False
  project: pcqm4m-contact
dataset:
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
  precompute_on_the_fly: True
posenc_Poly:
  enable: True
  add_full_edge_index: True
  method: deco_bern
  power: 14
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  enable_ckpt: False  # Checkpointing can now be disabled to save I/O when e.g. just benchmarking.
  ckpt_best: False  # WARNING: Checkpoint every epoch a better model is found may increase I/O significantly.
  ckpt_clean: True # Delete old ckpt each time.
  ckpt_period: 100
model:
  type: MbpModel
  loss_fun: cross_entropy
  edge_decoding: dot
MbpModel:
  enable: True
  hidden_dim: 80
  attn_heads: 8
  drop_prob: 0.0
  attn_drop_prob: 0.5
  residual: True
  layer_norm: False
  batch_norm: True
  bn_momentum: 0.1
  bn_no_runner: False
  rezero: False
  deg_scaler: True
  clamp: 5.0
  weight_fn: softmax
  agg: add
  act: relu
  pe_layer: simple_linear
  poly:
    layer_type: cattn
    num_blocks: 5
    repeats: 1
  full:
    layer_type: cattn
    enable: True
    repeats: 2
    input_norm: False
gnn:
  head: inductive_edge
  layers_post_mp: 1
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
