out_dir: results
metric_best: mrr
metric_agg: argmax
num_workers: 4
wandb:
  use: False
dataset:
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
  precompute_on_the_fly: True
posenc_Poly:
  enable: True
  add_full_edge_index: True
  method: deconet_bern
  power: 16
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_period: 100
  enable_ckpt: False  # Checkpointing can now be disabled to save I/O when e.g. just benchmarking.
  ckpt_best: False  # WARNING: Checkpoint every epoch a better model is found may increase I/O significantly.
model:
  type: DecoNet
  loss_fun: cross_entropy
  edge_decoding: dot
DecoNet:
  conv:
    num_layers: 6
    k1_hidden_dim: 64
    hidden_dim: 64
    bias: True
    batch_norm: True
    act: gelu
    drop_prob: 0.0
  gblock:
    layer_type: dot_prod_attn
    num_layers: 1
    hidden_dim: 96
    attn_heads: 8
    clamp: 5
    attn_drop_prob: 0.0
    drop_prob: 0.0
    weight_fn: softmax
    agg: add
    act: gelu
    bn_momentum: 0.1
  pe_layer: simple_linear
gnn:
  head: inductive_edge
  layers_post_mp: 1
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
