out_dir: results
metric_best: mae
metric_agg: argmin
accelerator: "cuda:0"
num_workers: 4
wandb:
  use: False
  project: peptides-struct
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_Poly:
  enable: True
  add_full_edge_index: True
  method: deco_bern
  power: 8
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  enable_ckpt: False  # Checkpointing can now be disabled to save I/O when e.g. just benchmarking.
  ckpt_best: False  # WARNING: Checkpoint every epoch a better model is found may increase I/O significantly.
model:
  type: DecoNet
  loss_fun: l1
  graph_pooling: mean
DecoNet:
  enable: True
  hidden_dim: 64
  attn_heads: 8
  drop_prob: 0.0
  attn_drop_prob: 0.2
  bn_momentum: 0.1
  deg_scaler: True
  bias: True
  clamp: 5.0
  weight_fn: softmax
  agg: add
  act: relu
  pe_layer: simple_linear
  conv:
    num_blocks: 2
    repeats: 1
  full:
    enable: True
    repeats: 1
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 1
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
