out_dir: results
metric_best: f1
wandb:
  use: False
  project: Pascal
dataset:
  format: PyG-VOCSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: VOCNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: VOCEdge
  edge_encoder_bn: False
posenc_Poly:
  enable: True
  add_full_edge_index: False
  method: low_middle_pass
  order: 8
  emb_dim: 10
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GseModel
  loss_fun: weighted_cross_entropy
gse_model:
  enable: True
  hidden_dim: 64
  attn_heads: 8
  drop_prob: 0.0
  attn_drop_prob: 0.2
  residual: True
  layer_norm: False
  batch_norm: True
  bn_momentum: 0.1
  bn_no_runner: False
  rezero: False
  deg_scaler: True
  clamp: 5.0
  weight_fn: softmax
  agg: add
  act: relu
  messaging:
    layer_type: grit
    num_blocks: 4
    repeats: 1
  full:
    layer_type: grit
    enable: True
    repeats: 1
    input_norm: False
  head: inductive_node
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
