out_dir: results
metric_best: accuracy-SBM
tensorboard_each_run: False  # Log to Tensorboard each run
accelerator: "cuda:0"
num_workers: 2
wandb:
  use: False
  project: CLUSTER
dataset:
  format: PyG-GNNBenchmarkDataset
  name: CLUSTER
  on_the_fly: True
  task: graph
  task_type: classification
  transductive: False
  split_mode: standard
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
posenc_Poly:
  enable: True
  method: mixed_bern
  order: 32
  emb_dim: 34
  add_full_edge_index: False
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: GseModel
  loss_fun: weighted_cross_entropy
  edge_decoding: dot
gse_model:
  enable: True
  hidden_dim: 56
  attn_heads: 8
  drop_prob: 0.01
  attn_drop_prob: 0.5
  residual: True
  layer_norm: False
  batch_norm: True
  bn_momentum: 0.1
  bn_no_runner: False
  rezero: False
  deg_scaler: True
  clamp: 5.0
  weight_fn: softmax
  agg: add
  act: relu
  messaging:
    layer_type: grit
    num_blocks: 6
    repeats: 2
  full:
    layer_type: dense
    enable: True
    repeats: 2
    input_norm: False
  head: inductive_node
gnn:
  head: inductive_node
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
