out_dir: results
metric_best: ap
accelerator: "cuda:0"
wandb:
  use: False
  project: molpcba
dataset:
  format: OGB
  name: ogbg-molpcba
  # on_the_fly: True
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_Poly:
  enable: True
  add_full_edge_index: True
  method: low_middle_pass
  order: 16
  emb_dim: 18
train:
  mode: custom
  batch_size: 512
  eval_period: 1
  ckpt_period: 20
model:
  type: GseModel
  loss_fun: cross_entropy
  graph_pooling: mean
gse_model:
  enable: True
  hidden_dim: 256
  attn_heads: 8
  drop_prob: 0.2
  attn_drop_prob: 0.25
  residual: True
  layer_norm: False
  batch_norm: True
  bn_momentum: 0.1
  bn_no_runner: False
  rezero: False
  deg_scaler: True
  clamp: 5.0
  weight_fn: softmax
  agg: add
  act: relu
  messaging:
    layer_type: grit
    num_blocks: 5
    repeats: 1
  full:
    layer_type: grit
    enable: True
    repeats: 1
    input_norm: False
  head: graph
optim:
  batch_accumulation: 1
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
