out_dir: results
metric_best: accuracy
tensorboard_each_run: False  # Log to Tensorboard each run
accelerator: "cuda:0"
num_workers: 2
wandb:
  use: False
  project: CIFAR10
dataset:
  format: PyG-GNNBenchmarkDataset
  name: CIFAR10
  on_the_fly: True
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
posenc_Poly:
  enable: True
  method: low_middle_pass
  order: 18
  emb_dim: 18
  add_full_edge_index: True
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: GseModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gse_model:
  enable: True
  hidden_dim: 52
  attn_heads: 4
  drop_prob: 0.0
  attn_drop_prob: 0.5
  residual: True
  layer_norm: False
  batch_norm: True
  bn_momentum: 0.1
  bn_no_runner: False
  rezero: False
  deg_scaler: True
  clamp: 5.0
  weight_fn: softmax
  agg: add
  act: relu
  messaging:
    layer_type: grit
    num_blocks: 0
    repeats: 0
  full:
    layer_type: grit
    enable: True
    repeats: 3
    input_norm: False
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 2
  batchnorm: False
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
